set_property SRC_FILE_INFO {cfile:D:/vivado_test/CRC_/crc/crc.srcs/constrs_1/new/system.xdc rfile:../../../crc.srcs/constrs_1/new/system.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4[ get_ports { clk } ]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14[ get_ports { rst_n } ]
